steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'install', 'package']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia.gcr.io/sound-repeater-245511/dsra:cloudbuild', '.']
images: ['asia.gcr.io/sound-repeater-245511/dsra']