steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/adi-tangidy/dsra-maven-project.git dsra-maven-project']
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['mvn', 'clean', 'install', 'package']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia.gcr.io/sound-repeater-245511/dsra:cloudbuild', '.']
images: ['asia.gcr.io/sound-repeater-245511/dsra']